def master_exists():     # Checks if the master password exists or not
    ...

def create_master_password():     # Creates the master password for the new users
    ...

def verify_master_password():     # Check if the master password extered by the user matches the actual password or not
    ...

def change_master_password():     # Allows the user to change the master password if they want to
    ...